# GENERATE TIME: Wed Dec 14 12:52:22 2022
# CMD:
# basicsr/train.py --local_rank=0 -opt options/train/BasicVSRPP/train_BasicVSRPPDATN_PatchV3_LRAM_GoPro.yml --launcher pytorch

# general settings
name: bsd3_STFANetpp
model_type: ModelVRT 
scale: 1
num_gpu: 1  # official: 8 GPUs
manual_seed: 0
reload: true
retrain: false
ratio: 0.25
no_fix_flow: true

# dataset and data loader settings
datasets:
  train:
    name: VideoDeblur
    type: DeblurRecurrentDataset
    dataroot_gt: /home/hczhang/datasets/BSD_BasicsrReorder/BSD_3ms24ms/train/gt
    dataroot_lq: /home/hczhang/datasets/BSD_BasicsrReorder/BSD_3ms24ms/train/blur
    meta_info_file: basicsr/data/meta_info/BSD_3ms24ms_train.txt
    val_partition: ~
    test_mode: False
    io_backend:
      type: disk
    file_end: png

    num_frame: 30
    gt_size: 256
    interval_list: [1]
    random_reverse: false
    use_hflip: False
    use_rot: false

    # data loader
    num_worker_per_gpu: 8
    batch_size_per_gpu: 1
    dataset_enlarge_ratio: 1000
    prefetch_mode: ~

  val:
    name: REDS4
    type: VideoRecurrentRVRTTestDataset
    dataroot_gt: /home/hczhang/datasets/BSD_BasicsrReorder/BSD_3ms24ms/test/gt
    dataroot_lq: /home/hczhang/datasets/BSD_BasicsrReorder/BSD_3ms24ms/test/blur

    cache_data: false
    io_backend:
      type: disk

    num_frame: -1

# network structures
network_g:
  type: STDANetPP
  # type: BasicVSRPlusPlus
  mid_channels: 144
  num_blocks: 3
  is_low_res_input: false
  spynet_path: model_zoo/pretrained_models/flownet/spynet_sintel_final-3d2a1287.pth


# path
path:
  pretrain_network_g: ~
  strict_load_g: True
  resume_state: ~

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 4e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [600000]
    restart_weights: [1.0]
    eta_min: [[1.0e-7,1.0e-7]]

  total_iter: 600000
  warmup_iter: 1000 # no warm up
  fix_flow: 30000

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1
    reduction: mean

# validation settings
val:
  val_freq: !!float 2.5e3
  # val_freq: !!float 1e2
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    # ssim:
      # type: calculate_ssim
      # crop_border: 0
      # test_y_channel: false

# logging settings
logger:
  print_freq: 500
  save_checkpoint_freq: !!float 2.5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~
    wandb_name: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29240


find_unused_parameters: true




